### ISSUE TITLE
How to get accountid from mnemonic

### ISSUE THREAD

**Issue by imloama** [jspschool/dart-stellar-sdk#2]
According [SEP-0005](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md),
I want to get accountid from mnemonic，but it's wrong, codes like
```
  final mnemonic = "illness spike retreat truth genius clock brain pass fit cave bargain toe";
  final seed = bip39.mnemonicToSeed(mnemonic);
  print(HEX.encode(seed));//correct
  final root = bip32.BIP32.fromSeed(seed);
  final path = root.derivePath("m/44'/148'/0'");
  KeyPair kp = KeyPair.fromSecretSeedList(path.privateKey);
  print(kp.accountId);//not GDRXE2BQUC3AZNPVFSCEZ76NJ3WWL25FYFK6RGZGIEKWE4SOOHSUJUJ6 
  print(kp.secretSeed);
```
[source codes](http://github.com/imloama/maxtoken/blob/master/test/seed_test.dart)

Environment:
flutter: 1.0.0
stellar: 0.3.2
bip39: 1.0.3
bip32: 1.0.5

Thx.

**Comment by imloama** [comment]
I create a repository to generate HD Wallet according [stellar-hd-wallet](https://github.com/chatch/stellar-hd-wallet).
My repository is [dart-stellar-hd-wallet](https://github.com/imloama/dart-stellar-hd-wallet)

**Comment by bas24** [comment]
> I create a repository to generate HD Wallet according [stellar-hd-wallet](https://github.com/chatch/stellar-hd-wallet).
> My repository is [dart-stellar-hd-wallet](https://github.com/imloama/dart-stellar-hd-wallet)

could you please give me insight WHY the same code decoding from the same seed or from the same mnemonic gives distinct results running in debug and building release version? Only tried on Android.

so, I'm getting different AccountId results where in debug that result is correct with 
var keyPair = stellar.KeyPair.fromSecretSeed(seed);
